name: nextlead
description: "A professional Lead Management CRM app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  animations: ^2.0.11
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"